name: titanic
channels:
  - conda-forge
dependencies:
  - numpy
  - scikit-learn>=0.22
  - matplotlib
  - pandas>=1.0
  - ipyaggrid==0.2.0
  - joblib==0.13.2
  - jupyter-datatables==0.3.8
  - panel==0.7.0
  - plotly==4.1.1
  - qgrid==1.2.0
  - seaborn==0.9.0
  - yellowbrick
  - graphviz